version: '3'
services:
  backend:
    build:
      context: ../backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/taskmanager
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user

  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: mysql
    restart: always
    ports:
      - 5432:5432
    environment:
      MYSQL_ROOT_PASSWORD: taskmanager
      MYSQL_DATABASE: taskmanager
      MYSQL_USER: root
      MYSQL_PASSWORD: root
